"""Deterministic ID->EN substitution for BKI domain terms before translation.

Targets are verified against the Rules corpus so retrieval matches the
source text. Order is longest-phrase-first so compounds win over parts.
"""
import re

# (id_phrase, en_term) ordered longest/most-specific first.
GLOSSARY = (
    # ── Longest compound phrases first ──
    ("jangkar daya cengkeram sangat tinggi", "very high holding power anchor"),
    ("baja tahan karat austenitik", "austenitic stainless steel"),
    ("faktor konsentrasi tegangan", "stress concentration factor"),
    ("dinding ujung bangunan atas", "superstructure end bulkhead"),
    ("perlindungan kebakaran struktural", "structural fire protection"),
    ("sistem penambatan titik tunggal", "single point mooring"),
    ("penutup palka kulit ganda", "double skin hatch cover"),
    ("sistem pendorong melintang", "transverse thruster"),
    ("daerah pelayaran tidak terbatas", "unlimited range of service"),
    ("garis air muat musim panas", "summer load waterline"),
    ("logam dengan titik leleh rendah", "low melting point metal"),
    ("pelayaran perairan terlindung", "sheltered water service"),
    ("bahan tidak mudah terbakar", "non-combustible material"),
    ("angka penunjuk perlengkapan", "equipment numeral"),
    ("daerah pelayaran terbatas", "restricted service range"),
    ("modulus penampang plastis", "plastic section modulus"),
    ("balok geladak memanjang", "deck longitudinal"),
    ("sumber daya darurat", "emergency source of power"),
    ("pengujian tak merusak", "non-destructive testing"),
    ("tangki penampung buangan", "slop tank"),
    ("penyangga baling-baling", "propeller bracket"),
    ("kondisi sarat muatan kosong", "light service draught"),
    ("modulus penampang", "section modulus"),
    ("momen lentur air tenang", "still water bending moment"),
    ("momen lentur gelombang", "wave bending moment"),
    ("gaya geser air tenang", "still water shear force"),
    ("gaya geser gelombang", "wave shear force"),
    ("penahan rantai haluan", "bow chain stopper"),
    ("tinggi lambung timbul", "freeboard"),
    ("jenis konstruksi melintang", "transverse framing system"),
    ("jenis konstruksi memanjang", "longitudinal framing system"),
    ("pelat lajur sisi geladak", "stringer plate"),
    ("baja tahan karat dupleks", "duplex stainless steel"),
    ("baja kekuatan tinggi", "higher strength steel"),
    ("baja kekuatan normal", "normal strength steel"),
    ("baja struktur lambung", "hull structural steel"),
    ("tekanan dinamis eksternal", "external dynamic pressure"),
    ("sarat subdivisi parsial", "partial subdivision draught"),
    ("sabuk es haluan atas", "upper forward ice belt"),
    ("kemudi semi-berbalans", "semi-spade rudder"),
    ("tambatan titik tunggal", "single point mooring"),
    ("beban putus minimum", "minimum breaking load"),
    ("penetrasi sebagian", "partial penetration"),
    ("tali penarik cadangan", "spare towrope"),
    ("bahan mudah terbakar", "combustible material"),
    ("kemiringan kapal", "trim"),
    ("tegangan luluh atas", "upper yield stress"),
    ("ketebalan film kering", "dry film thickness"),
    ("ketebalan pelat", "plate thickness"),
    ("penambahan korosi", "corrosion addition"),
    ("bentang tak tertumpu", "unsupported span"),
    ("perlindungan korosi", "corrosion protection"),
    ("pelat bukaan palka", "hatch opening plate"),
    ("gading geladak antara", "tween deck frame"),
    ("stabilitas kebocoran", "damage stability"),
    ("pelat kulit luar", "outer shell plating"),
    ("pelat alas dalam", "inner bottom plating"),
    ("kulit luar lambung", "hull shell"),
    ("beban yang bekerja", "acting loads"),
    ("kapal peti kemas", "container ship"),
    ("kapal penumpang", "passenger ship"),
    ("pembukaan palka", "hatch opening"),
    ("kapal kontainer", "container ship"),
    ("kapal tangki minyak", "oil tanker"),
    ("konstruksi melintang", "transverse framing"),
    ("konstruksi memanjang", "longitudinal framing"),
    ("ketebalan bersih", "net thickness"),
    ("jarak antar penegar", "stiffener spacing"),
    ("hantaman dasar", "bottom slamming"),
    ("geladak sekat", "bulkhead deck"),
    ("linggi buritan", "stern frame"),
    ("geladak kekuatan", "strength deck"),
    ("geladak cuaca", "weather deck"),
    ("anjungan", "bridge"),
    ("geladak antara", "tween deck"),
    ("balok melintang", "transverse"),
    ("balok memanjang", "longitudinal"),
    ("gading-gading", "frame"),
    ("garis tegak haluan", "forward perpendicular"),
    ("garis tegak buritan", "aft perpendicular"),
    ("bangunan atas", "superstructure"),
    ("sekat tubrukan", "collision bulkhead"),
    ("sekat melintang", "transverse bulkhead"),
    ("sekat memanjang", "longitudinal bulkhead"),
    ("pintu kedap cuaca", "weathertight door"),
    ("pintu kedap air", "watertight door"),
    ("pintu kebakaran", "fire door"),
    ("pintu haluan", "bow door"),
    ("geladak lambung timbul", "freeboard deck"),
    ("sarat pemisah", "subdivision draught"),
    ("jalan keluar", "escape route"),
    ("ambang palka", "hatch coaming"),
    ("bukaan palka", "hatch opening"),
    ("tutup palka", "hatch cover"),
    ("siku braket", "bracket"),
    ("sambungan las", "welded joint"),
    ("kampuh las", "weld groove"),
    ("gading besar", "web frame"),
    ("senta sisi", "stringer"),
    ("pelat geladak", "deck plating"),
    ("pelat sisi", "side shell plating"),
    ("ceruk haluan", "forepeak"),
    ("ceruk buritan", "afterpeak"),
    ("kapal tangki", "tanker"),
    ("kapal curah", "bulk carrier"),
    ("alat keselamatan", "life saving appliances"),
    ("las putus-putus", "intermittent weld"),
    ("sabuk es", "ice belt"),
    ("baja standar", "mild steel"),
    ("baja lunak", "mild steel"),
    ("baja tempa", "forged steel"),
    ("baja tuang", "cast steel"),
    ("baja tahan karat", "stainless steel"),
    ("lebar cetak", "moulded breadth"),
    ("tinggi cetak", "moulded depth"),
    ("lunas pelat datar", "flat plate keel"),
    ("lunas batang", "bar keel"),
    ("lunas bilga", "bilge keel"),
    ("lunas kotak", "box keel"),
    ("lunas dok", "docking keel"),
    ("sepatu lunas", "keel shoe"),
    ("wrang pelat", "plate floor"),
    ("wrang braket", "bracket floor"),
    ("wrang kedap air", "watertight floor"),
    ("koefisien balok", "block coefficient"),
    ("tangki balas", "ballast tank"),
    ("tangki kargo", "cargo tank"),
    ("tangki minyak nabati", "vegetable oil tank"),
    ("tangki minyak lumas", "lubrication oil tank"),
    ("tangki air tawar", "fresh water tank"),
    ("tangki air minum", "potable water tank"),
    ("tangki bahan bakar minyak", "fuel oil tank"),
    ("kemudi berbalans", "balanced rudder"),
    ("sepatu kemudi", "sole piece"),
    ("engsel kemudi", "pintle"),
    ("tanduk kemudi", "rudder horn"),
    ("tongkat kemudi", "rudder stock"),
    ("daun kemudi", "rudder blade"),
    ("linggi haluan", "stem"),
    ("kemudi", "rudder"),
    ("sekat bergelombang", "corrugated bulkhead"),
    ("sekat berlubang", "swash bulkhead"),
    ("sekat kedap air", "watertight bulkhead"),
    ("sekat ceruk buritan", "after peak bulkhead"),
    ("pelat lajur bilga", "bilge strake"),
    ("pelat lajur atas", "sheer strake"),
    ("ruang muat", "cargo hold"),
    ("fondasi mesin", "engine seating"),
    ("ruang kosong", "void space"),
    ("ruang permesinan", "machinery space"),
    ("ruang akomodasi", "accommodation space"),
    ("ruang pelayanan", "service space"),
    ("ruang perangkat kemudi", "steering gear room"),
    ("stasiun kontrol", "control station"),
    ("zona vertikal utama", "main vertical zone"),
    ("zona horizontal", "horizontal zone"),
    ("divisi kelas A", "A-class division"),
    ("divisi kelas B", "B-class division"),
    ("divisi kelas C", "C-class division"),
    ("selubung tangga", "stairway enclosure"),
    ("pagar pengaman", "guard rail"),
    ("tiang penyangga", "stanchion"),
    ("tiang sinyal", "signal mast"),
    ("sarat air ukuran", "scantling draught"),
    ("sarat air balas", "ballast draught"),
    ("penetrasi penuh", "full penetration"),
    ("las kontinu", "continuous weld"),
    ("las tumpul", "butt weld"),
    ("las sudut", "fillet weld"),
    ("tebal leher las", "weld throat thickness"),
    ("lambung timbul", "freeboard"),
    ("tinggi bebas", "freeboard"),
    ("paduan aluminium", "aluminium alloy"),
    ("titik leleh rendah", "low melting point"),
    ("bukan ekuivalen baja", "not steel equivalent"),
    ("notasi kelas IW", "Class Notation IW"),
    ("lambung bawah air", "underwater hull"),
    ("sistem pelapisan", "coating system"),
    ("cathodic protection", "cathodic protection"),
    ("anoda korban", "sacrificial anode"),
    ("arus tanding", "impressed current"),
    ("pelat lambung", "shell plating"),
    ("pelat dek", "deck plating"),
    ("pelat wrang", "floor plate"),
    ("pelat hadap", "face plate"),
    ("pelat bilah", "web plate"),
    ("pelat alas", "bottom shell plating"),
    ("pelat dasar", "bottom plating"),
    ("alas ganda", "double bottom"),
    ("dasar ganda", "double bottom"),
    ("pelat sisipan", "insert plate"),
    ("pelat kerah", "collar plate"),
    ("garis tegak", "perpendicular"),
    ("penahan rantai", "chain stopper"),
    ("rantai stud-link", "stud-link chain"),
    ("rantai jangkar", "chain cable"),
    ("penumpu geladak", "deck girder"),
    ("penumpu tengah", "centre girder"),
    ("penumpu samping", "side girder"),
    ("penumpu sisi palka", "hatch side girder"),
    ("penumpu es", "ice stringer"),
    ("balok geladak", "deck beam"),
    ("balok ujung palka", "hatch end beam"),
    ("gading pelintang", "side transverse"),
    ("gading utama", "main frame"),
    ("mesin jangkar", "windlass"),
    ("kubu-kubu", "bulwark"),
    ("ventilator", "ventilator"),
    ("helideck", "helideck"),
    ("landasan helikopter", "helideck"),
    ("geladak mobil", "car deck"),
    ("tongkang dorong", "pusher barge"),
    ("palka kargo", "cargo hatch"),
    ("palka cuaca", "weather deck hatch"),
    ("sudut palka", "hatchway corner"),
    ("lorong poros", "shaft tunnel"),
    ("pipa pelindung", "sleeve"),
    ("pipa udara", "air pipe"),
    ("pipa duga", "sounding pipe"),
    ("pipa limpah", "overflow pipe"),
    ("pipa kuras", "scupper"),
    ("lubang pembuangan air", "freeing port"),
    ("jendela kapal", "side scuttle"),
    ("jendela persegi", "window"),
    ("pintu buritan", "stern door"),
    ("pintu dalam", "inner door"),
    ("tali tambat", "mooring line"),
    ("tali tunda", "towline"),
    ("alat penyangga", "supporting device"),
    ("alat penahan", "securing device"),
    ("alat pengunci", "locking device"),
    ("penangkal ombak", "breakwater"),
    ("katup api", "fire damper"),
    ("kotak rantai", "chain locker"),
    ("peraturan lambung", "rules for hull"),
    ("panjang aturan", "rule length"),
    ("jarak gading", "frame spacing"),
    ("lebar efektif", "effective breadth"),
    ("momen inersia", "moment of inertia"),
    ("momen puntir", "torsional moment"),
    ("momen lentur", "bending moment"),
    ("tegangan lentur", "bending stress"),
    ("tegangan tarik", "tensile strength"),
    ("tegangan luluh", "yield stress"),
    ("tegangan geser", "shear stress"),
    ("tegangan normal", "normal stress"),
    ("tegangan sisa", "residual stress"),
    ("tegangan ekuivalen", "equivalent stress"),
    ("kekuatan tekuk", "buckling strength"),
    ("kekuatan fatik", "fatigue strength"),
    ("faktor material", "material factor"),
    ("beban desain", "design load"),
    ("beban geladak", "deck load"),
    ("beban muatan", "cargo load"),
    ("beban roda", "wheel load"),
    ("beban operasi", "operating load"),
    ("tekanan es", "ice pressure"),
    ("tekanan cairan", "liquid pressure"),
    ("penguatan es", "ice strengthening"),
    ("tabung poros", "stern tube"),
    ("stabilitas utuh", "intact stability"),
    ("haluan berumbi", "bulbous bow"),
    ("pelayaran pantai", "coasting service"),
    ("uji kekedapan", "tightness test"),
    ("kondisi pemuatan", "loading condition"),
    ("tarikan laut", "ocean towage"),
    ("pusat gravitasi", "centre of gravity"),
    ("kemudi pendorong", "thruster"),
    ("dalam air", "in-water"),
    ("titik luluh", "yield point"),
    ("rumah geladak", "deckhouse"),
    ("garis dasar", "base line"),
    ("notasi kelas", "Class Notation"),
    ("kapal barang", "cargo ship"),
    ("kapal pembawa bijih", "ore carrier"),
    ("kapal kombinasi", "combination carrier"),
    ("kapal tunda", "tug"),
    ("kapal suplai", "supply vessel"),
    ("kapal keruk", "dredger"),
    ("kapal niaga", "merchant ship"),
    ("sumur bilga", "bilge well"),
    ("dasar tunggal", "single bottom"),
    # ── Direction / position terms (Build 41) ──
    # These pin fore/aft direction so the 3B condense step cannot swap
    # 'buritan' (aft) to 'bow' or 'bagian haluan' (forward) to 'stern'.
    # The LLM sees the pre-substituted English and is told to keep it
    # verbatim. Only NON-AMBIGUOUS ship-direction phrases are included;
    # bare 'haluan'/'buritan'/'di depan'/'di belakang' are intentionally
    # NOT mapped (they appear in non-directional contexts, e.g. 'di depan
    # dermaga').
    ("di bagian buritan", "in the aft part"),
    ("bagian buritan", "aft part"),
    ("di bagian haluan", "in the forward part"),
    ("bagian haluan", "forward part"),
    ("di buritan", "at the aft"),
    ("buritan kapal", "aft end of the ship"),
    ("haluan kapal", "forward end of the ship"),
    ("di haluan", "at the forward"),
    # Freeing ports: pin the compound so condense cannot drift to
    # 'freeboard' (a different rule topic).
    ("freeing ports", "freeing ports"),
    ("freeing port", "freeing port"),
    ("lubang pembuangan air", "freeing port"),
    ("lubang pembuangan", "freeing port"),
    ("luas freeing", "freeing port area"),
    ("freeing port area", "freeing port area"),
    # ── Single words / shorter phrases last ──
    ("penampang", "section"),
    ("pengaku", "stiffener"),
    ("penegar", "stiffener"),
    ("penumpu", "girder"),
    ("gading", "frame"),
    ("hantaman", "slamming"),
    ("hentaman", "slamming"),
    ("senta", "stringer"),
    ("wrang", "floor"),
    ("sekat", "bulkhead"),
    ("sarat air", "draught"),
    ("akil", "forecastle"),
    ("kimbul", "poop"),
    ("bantalan kemudi", "rudder bearing"),
    ("ceruk", "peak"),
    ("koridor", "corridor"),
    ("koferdam", "cofferdam"),
    ("bantalan", "bearing"),
    ("tongkang", "barge"),
    ("ponton", "pontoon"),
    ("pilar", "pillar"),
    ("lorong", "trunk"),
    ("engsel", "hinged"),
)

_PATTERNS = tuple(
    (re.compile(r"\b" + re.escape(src) + r"\b", re.IGNORECASE), dst)
    for src, dst in GLOSSARY
)


def apply_glossary(query: str) -> str:
    """Replace known BKI domain phrases with corpus-verified English terms.

    Pure and deterministic. Compound phrases are applied first so that
    'tinggi bebas' -> 'freeboard' while bare 'tinggi' is left untouched
    (it is not a key) and therefore never becomes 'freeboard'.
    """
    out = query
    for pattern, dst in _PATTERNS:
        out = pattern.sub(dst, out)
    return out
